### PR TITLE
Fix Chainlight 005 // Introduce withdrawal delay and min deposit

### PR DESCRIPTION
**Pull request by filmakarov**
Fix [this](https://github.com/chainlight-io/2024-q4-biconomy-audit-issues-client/issues/5).

- Introduce submit request / execute request pattern for paymaster id balances withdrawals. Delay can be set to 0 for trusted paymasterIds though
- introduce min deposit. 

- [x] Introduce code changes
- [x] Fix tests

### CODE REVIEW

**Comment by livingrockrises** [comment]
let's merge below PR to develop first, take back merge and work on the test cases
https://github.com/bcnmy/gasdaddy/pull/28/files

**Comment by livingrockrises** [comment]
let's merge below PR to develop first, take back merge and work on the test cases
https://github.com/bcnmy/gasdaddy/pull/28/files

**Comment by filmakarov** [comment]
> let's merge below PR to develop first, take back merge and work on the test cases https://github.com/bcnmy/gasdaddy/pull/28/files

looking at it

**Comment by wooz3k-t** [comment]
Here's a minor suggestion.

- Emit an event in `setTrustedPaymasterId()`, `setMinDeposit()`, and `withdrawEth()`.
- Add `require(_trustedPaymasterIds[paymasterId] != isTrusted)` in `setTrustedPaymasterId()`.

**Comment by livingrockrises** [comment]
> Here's a minor suggestion.
> 
> * Emit an event in `setTrustedPaymasterId()`, `setMinDeposit()`, and `withdrawEth()`.
> * Add `require(_trustedPaymasterIds[paymasterId] != isTrusted)` in `setTrustedPaymasterId()`.

we thought these actions may not need event tracking. can still add @filmakarov

**Comment by filmakarov** [comment]
> Here's a minor suggestion.
> 
> * Emit an event in `setTrustedPaymasterId()`, `setMinDeposit()`, and `withdrawEth()`.
> * Add `require(_trustedPaymasterIds[paymasterId] != isTrusted)` in `setTrustedPaymasterId()`.

addressed here https://github.com/bcnmy/gasdaddy/pull/27/commits/36fb443a3518fe22b69eff9afa3ba1710164960f

**Review by livingrockrises — APPROVED** [review]

**Pull request merged**
